### ISSUE TITLE
German datetime  

### ISSUE THREAD

**Issue by l5t** [wit-ai/duckling#91]
@hactar did an awesome job at starting the support of datetime in duckling and explained very well the current issue. We would love to get some help from the community here to complete it
https://github.com/wit-ai/wit/issues/212

**Comment by hactar** [comment]
I've updated https://github.com/hactar/duckling to 0.4.0-alpha and moved the german files to the corresponding new folders so that it can be pulled in easily. The issues of https://github.com/wit-ai/wit/issues/212 still persist so I haven't submitted a pull request.

**Comment by petr-tik** [comment]
I ran into the same problem in [my branch](https://github.com/petr-tik/duckling/tree/german_numbers_new/resources/languages/de). 

I would love to help out and crack this one together

**Comment by patapizza** [comment]
For partial work, you can prepend the files that don't work with an underscore (`_`), submit a PR, and open an issue with the `help wanted` tag (this one).

**Comment by hactar** [comment]
@petr-tik if you can solve the issues then yes please, I'll pull in any solutions you have.

@patapizza so in this case i would prepend all files in de/rules or also the files in corpus?

**Comment by patapizza** [comment]
@hactar The ones that don't work, both in `rules` and in `corpus`.

**Comment by jimregan** [comment]
I think I got this to work, using the sort of regex I wouldn't like my mother to know I've used: https://github.com/hactar/duckling/pull/2

**Comment by ar7hur** [comment]
Hey @hactar @jimregan @petr-tik thanks for your contributions! I'm the original author of Duckling and even if I used to speak some German, I didn't really take this kind of situation into account.

Your regex option is not that horrible, but it won't scale beautifully for larger number because everything will need to be in one big regex. Now, you could argue that very few people will write numbers in the millions in full letters, so we might live with the regex.

The best long term solution would be to add an option on some rules to tell them NOT to worry about whitespace. The way it works now, rules try to match their individual parts, and THEN check that what's in between can be considered whitespace. See [this function](https://github.com/wit-ai/duckling/blob/3f9c29176556840692fe53df358ef95425c7272e/src/duckling/engine.clj#L110). That's not super hard to do, but the rules DSL would become a little bit less clean (to support the option).

Please let me know if the regex route is good enough for now. And thanks again!

**Comment by hactar** [comment]
My opinion is that, for now, the regex solution is sufficient, as long as we could get it running for up to 999, the currently supports up to 99. I'd love to write a function for 
`#"(?i)(ein|zwei|drei|vier|fünf|sechs|sieben|acht|neun)hundert(ein|zwei|drei|vier|fünf|sechs|sieben|acht|neun)und(zwanzig|dreissig|vierzig|fünfzig|sechzig|siebzig|achtzig|neunzig)"`
but I cant figure out how that would work (for starters I guess I'd need ":groups third" and that doesn't exist?

That said, https://github.com/hactar/duckling is pretty much ready to pull except for the last 2 test fails (the other 318 pass, yeay!):

`0 FAIL "25.4. um 4"
    Expected {:start #object[org.joda.time.DateTime 0x7b6eed5e "2013-04-25T16:00:00.000-02:00"], :grain :minute}
    Got      25
    Got      4
    Got      4
    Got      25
    Got      4
    Got      {:start #object[org.joda.time.DateTime 0x4115329b "2013-04-25T04:00:00.000-02:00"], :grain :hour}
1 FAIL "morgen um 3"
    Expected {:start #object[org.joda.time.DateTime 0x16f83065 "2013-02-13T15:00:00.000-02:00"], :grain :hour}
    Got      3
    Got      {:start #object[org.joda.time.DateTime 0x68c04973 "2013-02-13T03:00:00.000-02:00"], :grain :hour}
:de$core: 320 examples, 2 failed.`

The issue is the 12 vs 24 hour thing. When a user says "um 3" he probably means 15:00, and this works. But when linked with "morgen um 3" (tomorrow at 3), the rules currently prefer the next day at 3:00 am. The same goes for the second failure (4 should be primarily identified as 16:00 and not 4 in the morning). I can't figure out how to adjust the rules to reflect this.

Playing does contain the correct value as one of the subvalues, but not as the main value:

`duckling.core=> (play :de$core "morgen um 3")
W -----------   7 | time      | intersect                 | P = -11.8421 | tomorrow + at <time-
         ----   6 | time      | at <time-of-day>          | P = -3.3219 |  + time-of-day (late
            -   5 | null      | number (as relative minutes) | P = -1.1324 | integer (numeric)
            -   4 | time      | time-of-day (latent)      | P = -0.6062 | integer (numeric)
            -   3 | time      | year (latent)             | P = -0.8918 | integer (numeric)
  ------        2 | time      | tomorrow                  | P = -0.2513 | 
W           -   1 | number    | integer (numeric)         | P = -0.1187 | 
  morgen um 3

2 winners:
number                    {:type "value", :value 3} {:integer true}
time                      {:type "value", :value "2013-02-13T03:00:00.000-02:00", :grain :hour, :values ({:type "value", :value "2013-02-13T03:00:00.000-02:00", :grain :hour} {:type "value", :value "2013-02-13T15:00:00.000-02:00", :grain :hour})} {:direction nil}
For further info: (details idx) where 1 <= idx <= 7`  

If someone could fix these final two tests then number and datetime in German is good to go.

**Comment by jimregan** [comment]
I've been playing with it a little more, and the last version of the regex I'd had looked like this:
```
(?i)(((ein|zwei|drei|vier|fünf|sechs|sieben|acht|neun)?hundert)?((ein|zwei|drei|vier|fünf|sechs|sieben|acht|neun)und)?((zwanzig|dreissig|vierzig|fünfzig|sechszig|sibzig|achtzig|neunzig|dreizehn|vierzehn|fünfzehn|sechzehn|siebzehn|achtzehn|neunzehn|eins?|zwei|drei|vier|fünf|sechs|sieben|acht|neun|zehn|elf|zwölf)?tausend)?((ein|zwei|drei|vier|fünf|sechs|sieben|acht|neun)?hundert)?((ein|zwei|drei|vier|fünf|sechs|sieben|acht|neun)und)?(zwanzig|dreissig|vierzig|fünfzig|sechszig|sibzig|achtzig|neunzig|dreizehn|vierzehn|fünfzehn|sechzehn|siebzehn|achtzehn|neunzehn|eins?|zwei|drei|vier|fünf|sechs|sieben|acht|neun|zehn|elf|zwölf)?)
```
...and that still systematically misses some pieces, that I'm looking at now

":groups third" would be nice, but not necessary, because you can just use a cascade of regexes and build up the number in stages.

**Comment by hactar** [comment]
@jimregan looks like fun ;) I was actually thinking of simply splitting it into 3 rules, < 100, 111-129, and 101-110/121-999 but yours might be cleaner. Send me a PR when you're done.

**Comment by jimregan** [comment]
I was thinking of going as far as 999,999 :)
There's something I want to try, but I've got overdue assignments to finish first.

**Comment by helgetan** [comment]
hey any updates on this topic? i need datetime in a project so it would be really helpful to get this to work :)

**Comment by hactar** [comment]
As there's been no movement here for weeks, I've created a pull request because while it isn't perfect, I would say its good enough and better than nothing :).

**Comment by l5t** [comment]
We just released it on Wit... Thanks a lot for your contributions @hactar @petr-tik  and @helgetan  
Would love to tweet about it and mention you if you have a twitter handle
![13330442_278304869184505_1054406546_n](https://cloud.githubusercontent.com/assets/6992759/15751785/417cffc8-28a0-11e6-92c0-e8b83dca1ab7.png)

**Comment by petr-tik** [comment]
Great to hear!! Twitter handle: Petr_tik

Cheers

**Comment by hactar** [comment]
Yeay! Looks like its working :) Im "PatrickWolowicz" on twitter.

<img width="996" alt="cursor_and_wit_console" src="https://cloud.githubusercontent.com/assets/645674/15752232/77762ea4-28ed-11e6-96c6-a0debe1c7f76.png">

**Comment by jimregan** [comment]
Great! I'm 'jimregan' on Twitter
